---
title: "exploracion"
author: "González, Jorge / Shifres, Juan"
date: "2023-08-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(dplyr)
library(lubridate)
```

```{r}
datos <- read.csv("datos/df_filtrado.csv")
```

```{r}
#listo los nombres de variables
names(datos)
```

```{r}
# resumen de los estadísticos del dataset
summary(datos)
```

Transformo las fechas.
```{r}
datos <- datos |> 
  mutate(FECHA_APERTURA = ymd(FECHA_APERTURA), 
            FIS = ymd(FIS), 
            FECHA_INTERNACION = ymd(FECHA_INTERNACION), 
            FECHA_CUI_INTENSIVOS = ymd(FECHA_CUI_INTENSIVOS), 
            FECHA_FALLECIMIENTO = ymd(FECHA_FALLECIMIENTO))
```

```{r}
boxplot(datos$EDAD_DIAGNOSTICO, outline = F)
```

```{r}
hist(datos$EDAD_DIAGNOSTICO)
```

```{r}
hist(datos$SEPI_APERTURA)
```
Acá vemos que el pico se produce a partir de la semana epidemiológica 24 (junio) con lo cual coincide con el comienzo de la época invernal.







